test

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -12,20 +12,16 @@ SDK_PATH_FILTER="sdk/"
 # List of changed files
 CONTRACTS_PATH_CHANGES=()
 SDK_PATH_CHANGES=()
-# CONTRACTS_CHANGE_DETECTED=0
-# SDK_CHANGE_DETECTED=0
 
-# Get list of all `git add` files to be committed
+# Get list of all changes since last commit
 GIT_ADDED_FILE_LIST=($(git diff --name-only HEAD))
 
 # Iterate through staged files to update filters
 for FILE in "${GIT_ADDED_FILE_LIST[@]}"; do
     if [[ $FILE =~ ^"$CONTRACTS_PATH_FILTER" ]]; then 
         CONTRACTS_PATH_CHANGES+=($FILE)
-        # CONTRACTS_CHANGE_DETECTED=1
     elif [[ $FILE =~ ^"$SDK_PATH_FILTER" ]]; then 
         SDK_CHANGE_DETECTED+=($FILE)
-        # SDK_CHANGE_DETECTED=1
     fi
 done
 
@@ -33,17 +29,38 @@ echo $CONTRACTS_PATH_CHANGES
 echo $SDK_PATH_CHANGES
 
 # Selective linting based on filters
-# if [ $CONTRACTS_CHANGE_DETECTED -eq 1 ]; then
-#     echo "$CONTRACTS_PATH_FILTER files are changed, linting..."
-#     cd contracts
-#     if [ ! -d "node_modules" ]; then
-#         echo "Error: missing dependencies in $CONTRACTS_PATH_FILTER"
-#         exit 1
-#     fi
-#     pnpm run lint
-#     cd ..
-#     git update-index --again
-# fi
+if [[ ${#CONTRACTS_PATH_CHANGES[@]} -gt 0 ]]; then
+    cd $CONTRACTS_PATH_FILTER
+    if [ ! -d "node_modules" ]; then
+        echo "Error: missing dependencies in $CONTRACTS_PATH_FILTER"
+        exit 1
+    fi
+
+    TYPESCRIPT_FILE_FOUND=0
+    SOLIDITY_FILE_FOUND=0
+
+    for FILE in "${CONTRACTS_PATH_CHANGES[@]}"; do
+        if [[ $FILE =~ $TYPESCRIPT_FILTER ]]; then 
+            TYPESCRIPT_FILE_FOUND=1
+        elif [[ $FILE =~ $SOLIDITY_FILTER ]]; then 
+            SOLIDITY_FILE_FOUND=1
+        fi
+    done
+
+    if [ $TYPESCRIPT_FILE_FOUND -eq 1 ]; then
+        echo "*.ts files changed in $CONTRACTS_PATH_FILTER, linting..."
+        pnpm run lint:ts
+    fi
+
+    if [ $SOLIDITY_FILE_FOUND -eq 1 ]; then
+        echo "*.sol files changed in $CONTRACTS_PATH_FILTER, linting..."
+        pnpm run lint:sol
+    fi
+
+
+    cd ..
+    git update-index --again
+fi
 
 # if [ $SDK_CHANGE_DETECTED -eq 1 ]; then
 #     echo "$SDK_PATH_FILTER files are changed, linting..."
