fix: manual release flow

diff --git a/.github/workflows/linea-tracer-plugin-release.yml b/.github/workflows/linea-tracer-plugin-release.yml
--- a/.github/workflows/linea-tracer-plugin-release.yml
+++ b/.github/workflows/linea-tracer-plugin-release.yml
@@ -6,14 +6,13 @@ permissions:
   packages: write
 
 on:
-  release:
   workflow_dispatch:
     inputs:
       release_tag:
-        description: Specify tag where assets should be added.
+        description: Specify tag where assets should be added. (Must prefix with "linea-tracer-")
         required: true
         type: string
-        default: "v1.2.3"
+        default: "linea-tracer-beta-v4.4-rc7"
 
 jobs:
   # ==================================================================
@@ -21,7 +20,24 @@ jobs:
   # ==================================================================
   build:
     runs-on: ubuntu-latest
+    outputs:
+      createTag: ${{ steps.upload-assets.outputs.CREATE_TAG }}
+      releaseTag: ${{ steps.config.outputs.RELEASE_TAG }}
+      versionTag: ${{ steps.config.outputs.VERSION_TAG }}
     steps:
+      - name: Configure Tag
+        id: config
+        # set tag to use in subsequent steps.
+        run: |
+          if [[ "$tag_name" != "linea-tracer-"* ]]; then
+            echo "Error: The given 'inputs.release_tag' or 'release.tag_name' ($tag_name) does not start with 'linea-tracer-'"
+            exit 1
+          fi
+          echo "VERSION_TAG=${tag_name#linea-tracer-}" >> $GITHUB_OUTPUT
+          echo "RELEASE_TAG=${tag_name}" >> $GITHUB_OUTPUT
+        env:
+          tag_name: ${{ inputs.release_tag || github.event.release.tag_name }}
+
       - name: Checkout repository
         uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
         with:
@@ -31,27 +47,19 @@ jobs:
         # setup go-corset
         uses: ./.github/actions/setup-tracer-environment
 
-      - name: Configure Tag
-        id: config
-        # set tag to use in subsequent steps.
-        run: |
-          echo "VERSION_TAG=${tag_name#linea-tracer-}" >> $GITHUB_OUTPUT
-          echo "RELEASE_TAG=${tag_name}" >> $GITHUB_OUTPUT
-        env:
-          tag_name: ${{ inputs.release_tag || github.event.release.tag_name }}
-
       - name: Build Assets
         run: ./gradlew :tracer:artifacts -PreleaseVersion=${{ steps.config.outputs.VERSION_TAG }}
         env:
           JAVA_OPTS: -Xmx2g -Dorg.gradle.daemon=false
 
       - name: Upload Assets
+        id: upload-assets
         run: |
-          gh release upload ${{ steps.config.outputs.RELEASE_TAG }} $jar_asset
+          echo "CREATE_TAG=$(gh release create "${{ steps.config.outputs.RELEASE_TAG }}" $jar_asset --target "${{ github.ref }}" 2>&1)" >> $GITHUB_OUTPUT
           gh release upload ${{ steps.config.outputs.RELEASE_TAG }} $zip_asset
         env:
-          jar_asset: ${{ github.workspace }}/tracer/plugins/build/libs/linea-tracer-${{ steps.config.outputs.VERSION_TAG }}.jar
-          zip_asset: ${{ github.workspace }}/tracer/plugins/build/distributions/linea-tracer-${{ steps.config.outputs.VERSION_TAG }}.zip
+          jar_asset: ./tracer/plugins/build/libs/linea-tracer-${{ steps.config.outputs.VERSION_TAG }}.jar
+          zip_asset: ./tracer/plugins/build/distributions/linea-tracer-${{ steps.config.outputs.VERSION_TAG }}.zip
           GH_TOKEN: ${{ github.token }}
 
       - name: Set up GCC
@@ -72,42 +80,28 @@ jobs:
         run: ./gradlew --no-daemon --parallel :tracer:clean :tracer:spotlessCheck
 
   # ==================================================================
+  # Delete created tag on build failure
+  # ==================================================================
+
+  delete-tag-on-failure:
+    needs: [ build ]
+    if: always() && needs.build.result == 'failure'
+    runs-on: ubuntu-latest
+    steps:
+      - name: Delete tag created without release
+        run: |
+          if [[ "${{ needs.build.outputs.createTag }}" != "a release with the same tag name already exists:"* ]]; then
+            delete_output=$(gh release delete "${{needs.build.outputs.releaseTag}}" --repo "${{ github.repository }}" --cleanup-tag --yes 2>&1) || [[ "${delete_output}" == "release not found" ]]
+            echo "Deleted tag and release: ${{ needs.build.outputs.releaseTag }}";
+          else
+            echo "${{ needs.build.outputs.createTag }}";
+          fi
+        env:
+          GH_TOKEN: ${{ github.token }}
+
+  # ==================================================================
   # Unit Tests
   # ==================================================================
-  unit-tests-london:
-    needs: [ build ]
-    uses: ./.github/workflows/reusable-tracer-unit-tests.yml
-    with:
-      zkevm_fork: LONDON
-      tests-with-ssh: false
-
-  unit-tests-paris:
-    needs: [ build ]
-    uses: ./.github/workflows/reusable-tracer-unit-tests.yml
-    with:
-      zkevm_fork: PARIS
-      tests-with-ssh: false
-
-  unit-tests-shanghai:
-    needs: [ build ]
-    uses: ./.github/workflows/reusable-tracer-unit-tests.yml
-    with:
-      zkevm_fork: SHANGHAI
-      tests-with-ssh: false
-
-  unit-tests-cancun:
-    needs: [ build ]
-    uses: ./.github/workflows/reusable-tracer-unit-tests.yml
-    with:
-      zkevm_fork: CANCUN
-      tests-with-ssh: false
-
-  unit-tests-prague:
-    needs: [ build ]
-    uses: ./.github/workflows/reusable-tracer-unit-tests.yml
-    with:
-      zkevm_fork: PRAGUE
-      tests-with-ssh: false
 
   unit-tests-osaka:
     needs: [ build ]
@@ -134,7 +128,7 @@ jobs:
           enable-ssh: false
 
       - name: Run replay tests
-        run: GOMEMLIMIT=26GiB ./gradlew :arithmetization:fastReplayTests
+        run: GOMEMLIMIT=26GiB ./gradlew :tracer:arithmetization:fastReplayTests
         env:
           JAVA_OPTS: -Dorg.gradle.daemon=false
           JUNIT_TESTS_PARALLELISM: 4
@@ -163,7 +157,7 @@ jobs:
           path: tracer/arithmetization/build/jacoco/fastReplayTests.exec
 
   # ==================================================================
-  # Publish release post tests
+  # Publish release
   # ==================================================================
   publish:
     needs: [ build ]
@@ -181,7 +175,7 @@ jobs:
         uses: ./.github/actions/setup-tracer-environment
 
       - name: Publish Java artifacts
-        run: ./gradlew :tracer:publish
+        run: ./gradlew :tracer:publish -PreleaseVersion=${{needs.build.outputs.versionTag}}
         env:
           CLOUDSMITH_USER: ${{ secrets.CLOUDSMITH_USER }}
           CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
