Only delete if tag was not preexisting

diff --git a/.github/workflows/linea-tracer-plugin-release.yml b/.github/workflows/linea-tracer-plugin-release.yml
--- a/.github/workflows/linea-tracer-plugin-release.yml
+++ b/.github/workflows/linea-tracer-plugin-release.yml
@@ -51,11 +51,10 @@ jobs:
 
       - name: Upload Assets
         id: upload-assets
-        continue-on-error: true
         run: |
           gh release delete linea-tracer-test-release-dummy --cleanup-tag
           gh release delete linea-tracer-beta-v4.4-rc7 --cleanup-tag
-          gh release create ${{ steps.config.outputs.RELEASE_TAG }} $jar_asset
+          echo "create_tag=${gh release create ${{ steps.config.outputs.RELEASE_TAG }} $jar_asset}" >> $GITHUB_OUTPUT
           gh release upload ${{ steps.config.outputs.RELEASE_TAG }} $zip_asset
         env:
           jar_asset: ./tracer/plugins/build/libs/linea-tracer-${{ steps.config.outputs.VERSION_TAG }}.jar
@@ -64,19 +63,16 @@ jobs:
 
       - name: Set up GCC
         id: setup-gcc
-        continue-on-error: true
         uses: egor-tensin/setup-gcc@eaa888eb19115a521fa72b65cd94fe1f25bbcaac #v1.3
 
       - name: Build without tests
         id: build-without-tests
-        continue-on-error: true
         run: ./gradlew :tracer:build -x test -x spotlessCheck
         env:
           JAVA_OPTS: -Xmx2g -Dorg.gradle.daemon=false
 
       - name: Store distribution artifacts
         id : store-artifacts
-        continue-on-error: true
         uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
         with:
           name: distributions
@@ -84,13 +80,23 @@ jobs:
 
       - name: Run spotless
         id: run-spotless
-        continue-on-error: true
         run: ./gradlew --no-daemon --parallel :tracer:clean :tracer:spotlessCheck
 
+  # ==================================================================
+  # Delete created tag in case following steps failed
+  # ==================================================================
+
+  delete-tag-on-failure:
+    needs: [ build ]
+    if: needs.build.result == 'failure'
+    runs-on: ubuntu-latest
+    steps:
       - name: Delete tag created without release
-        if: steps.upload-assets.outcome == 'failure' || steps.setup-gcc.outcome  == 'failure' || steps.build-without-tests.outcome == 'failure' || steps.store-artifacts.outcome == 'failure' || steps.run-spotless.outcome == 'failure'
         run: |
-          delete_output=$(gh release delete "${{steps.config.outputs.RELEASE_TAG}}" --cleanup-tag --yes 2>&1) || [[ "${delete_output}" == "release not found" ]]
+          if [[ ${{needs.build.outputs.create_tag}} != "a release with the same tag name already exists:"* ]]; then
+            delete_output=$(gh release delete "${{needs.build.outputs.releaseTag}}" --cleanup-tag --yes 2>&1) || [[ "${delete_output}" == "release not found" ]]
+            exit 1
+          fi
         env:
           GH_TOKEN: ${{ github.token }}
 
